# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d290671ddb8f544001027169f6e6090f830805b98b6b102e10f045774507f057d20466d48a2ae388d3b8ecd91b9dac4e5acd89a0d6d3c8a37147e97377b20a5c

test:
  secret_key_base: 98398983b0cdaec004624365ebf6cc8ddb8271ad1b4694f651c468264d8faf748bf33cf741bdb9572ee6c8cfb2b0cd19809b23c3f23c0f87e15a2738fbffa5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
